ASTROLOGY_TERMS = {
    # Planets (Navagrahas)
    "sun": {"ta": "சூரியன்", "en": "Sun"},
    "moon": {"ta": "சந்திரன்", "en": "Moon"},
    "mars": {"ta": "செவ்வாய்", "en": "Mars"},
    "mercury": {"ta": "புதன்", "en": "Mercury"},
    "jupiter": {"ta": "குரு", "en": "Jupiter"},
    "venus": {"ta": "சுக்கிரன்", "en": "Venus"},
    "saturn": {"ta": "சனி", "en": "Saturn"},
    "rahu": {"ta": "ராகு", "en": "Rahu"},
    "ketu": {"ta": "கேது", "en": "Ketu"},
    
    # Doshams (தோஷம்)
    "sevvai_dosham": {"ta": "செவ்வாய் தோஷம்", "en": "Mars Dosham"},
    "sani_dosham": {"ta": "சனி தோஷம்", "en": "Saturn Dosham"},
    "rahu_dosham": {"ta": "ராகு தோஷம்", "en": "Rahu Dosham"},
    "ketu_dosham": {"ta": "கேது தோஷம்", "en": "Ketu Dosham"},
    "mangalik_dosham": {"ta": "மங்களிக தோஷம்", "en": "Mangalik Dosham"},
    "kuja_dosha": {"ta": "குஜ தோஷம்", "en": "Kuja Dosha"},
    "kaalsarpa_dosha": {"ta": "காலசர்ப தோஷம்", "en": "Kaalsarpa Dosha"},
    "pitru_dosha": {"ta": "பித்ரு தோஷம்", "en": "Pitru Dosha"},
    "naga_dosha": {"ta": "நாக தோஷம்", "en": "Naga Dosha"},
    
    # Nakshatras (நட்சத்திரங்கள்) - All 27
    "ashwini": {"ta": "அசுவினி", "en": "Ashwini"},
    "bharani": {"ta": "பரணி", "en": "Bharani"},
    "krittika": {"ta": "கிருத்திகை", "en": "Krittika"},
    "rohini": {"ta": "ரோகிணி", "en": "Rohini"},
    "mrigasira": {"ta": "மிருகசீரிஷம்", "en": "Mrigasira"},
    "ardra": {"ta": "திருவாதிரை", "en": "Ardra"},
    "punarvasu": {"ta": "புனர்பூசம்", "en": "Punarvasu"},
    "pushya": {"ta": "பூசம்", "en": "Pushya"},
    "ashlesha": {"ta": "ஆயில்யம்", "en": "Ashlesha"},
    "magha": {"ta": "மகம்", "en": "Magha"},
    "purva_phalguni": {"ta": "பூரம்", "en": "Purva Phalguni"},
    "uttara_phalguni": {"ta": "உத்திரம்", "en": "Uttara Phalguni"},
    "hasta": {"ta": "ஹஸ்தம்", "en": "Hasta"},
    "chitra": {"ta": "சித்திரை", "en": "Chitra"},
    "swati": {"ta": "சுவாதி", "en": "Swati"},
    "vishaka": {"ta": "விசாகம்", "en": "Vishaka"},
    "anuradha": {"ta": "அனுஷம்", "en": "Anuradha"},
    "jyeshtha": {"ta": "கேட்டை", "en": "Jyeshtha"},
    "mula": {"ta": "மூலம்", "en": "Mula"},
    "purva_ashadha": {"ta": "பூராடம்", "en": "Purva Ashadha"},
    "uttara_ashadha": {"ta": "உத்திராடம்", "en": "Uttara Ashadha"},
    "shravana": {"ta": "திருவோணம்", "en": "Shravana"},
    "dhanishta": {"ta": "அவிட்டம்", "en": "Dhanishta"},
    "shatabhisha": {"ta": "சதயம்", "en": "Shatabhisha"},
    "purva_bhadrapada": {"ta": "பூரட்டாதி", "en": "Purva Bhadrapada"},
    "uttara_bhadrapada": {"ta": "உத்திரட்டாதி", "en": "Uttara Bhadrapada"},
    "revati": {"ta": "ரேவதி", "en": "Revati"},
    
    # Rashis (ராசிகள்) - All 12
    "mesha": {"ta": "மேஷம்", "en": "Aries"},
    "rishabha": {"ta": "ரிஷபம்", "en": "Taurus"},
    "mithuna": {"ta": "மிதுனம்", "en": "Gemini"},
    "kataka": {"ta": "கடகம்", "en": "Cancer"},
    "simha": {"ta": "சிம்மம்", "en": "Leo"},
    "kanya": {"ta": "கன்னி", "en": "Virgo"},
    "tula": {"ta": "துலாம்", "en": "Libra"},
    "vrishchika": {"ta": "விருச்சிகம்", "en": "Scorpio"},
    "dhanu": {"ta": "தனுசு", "en": "Sagittarius"},
    "makara": {"ta": "மகரம்", "en": "Capricorn"},
    "kumbha": {"ta": "கும்பம்", "en": "Aquarius"},
    "meena": {"ta": "மீனம்", "en": "Pisces"},
    
    # Houses (Bhavas)
    "first_house": {"ta": "முதல் வீடு", "en": "First House"},
    "second_house": {"ta": "இரண்டாம் வீடு", "en": "Second House"},
    "third_house": {"ta": "மூன்றாம் வீடு", "en": "Third House"},
    "fourth_house": {"ta": "நான்காம் வீடு", "en": "Fourth House"},
    "fifth_house": {"ta": "ஐந்தாம் வீடு", "en": "Fifth House"},
    "sixth_house": {"ta": "ஆறாம் வீடு", "en": "Sixth House"},
    "seventh_house": {"ta": "ஏழாம் வீடு", "en": "Seventh House"},
    "eighth_house": {"ta": "எட்டாம் வீடு", "en": "Eighth House"},
    "ninth_house": {"ta": "ஒன்பதாம் வீடு", "en": "Ninth House"},
    "tenth_house": {"ta": "பத்தாம் வீடு", "en": "Tenth House"},
    "eleventh_house": {"ta": "பதினொன்றாம் வீடு", "en": "Eleventh House"},
    "twelfth_house": {"ta": "பன்னிரண்டாம் வீடு", "en": "Twelfth House"},
    
    # Dashas (Major Periods)
    "sun_dasha": {"ta": "சூரிய தசா", "en": "Sun Dasha"},
    "moon_dasha": {"ta": "சந்திர தசா", "en": "Moon Dasha"},
    "mars_dasha": {"ta": "செவ்வாய் தசா", "en": "Mars Dasha"},
    "mercury_dasha": {"ta": "புதன் தசா", "en": "Mercury Dasha"},
    "jupiter_dasha": {"ta": "குரு தசா", "en": "Jupiter Dasha"},
    "venus_dasha": {"ta": "சுக்கிர தசா", "en": "Venus Dasha"},
    "saturn_dasha": {"ta": "சனி தசா", "en": "Saturn Dasha"},
    "rahu_dasha": {"ta": "ராகு தசா", "en": "Rahu Dasha"},
    "ketu_dasha": {"ta": "கேது தசா", "en": "Ketu Dasha"},
    "mahadasha": {"ta": "மகாதசா", "en": "Mahadasha"},
    "antardasha": {"ta": "அந்தர்தசா", "en": "Antardasha"},
    
    # Yogas (Planetary Combinations)
    "gajakesari_yoga": {"ta": "கஜகேசரி யோகம்", "en": "Gajakesari Yoga"},
    "chandra_mangala_yoga": {"ta": "சந்திர மங்கள யோகம்", "en": "Chandra Mangala Yoga"},
    "budha_aditya_yoga": {"ta": "புத ஆதித்ய யோகம்", "en": "Budha Aditya Yoga"},
    "amala_yoga": {"ta": "அமல யோகம்", "en": "Amala Yoga"},
    "parvata_yoga": {"ta": "பர்வத யோகம்", "en": "Parvata Yoga"},
    "raja_yoga": {"ta": "ராஜ யோகம்", "en": "Raja Yoga"},
    "dhana_yoga": {"ta": "தன யோகம்", "en": "Dhana Yoga"},
    "panchamahapurusha_yoga": {"ta": "பஞ்சமஹாபுருஷ யோகம்", "en": "Panchamahapurusha Yoga"},
    "viparita_raja_yoga": {"ta": "விபரீத ராஜ யோகம்", "en": "Viparita Raja Yoga"},
    "shasha_yoga": {"ta": "சஷ யோகம்", "en": "Shasha Yoga"},
    "vesi_yoga": {"ta": "வேசி யோகம்", "en": "Vesi Yoga"},
    "vasumati_yoga": {"ta": "வாசுமதி யோகம்", "en": "Vasumati Yoga"},
    
    # General Terms
    "horoscope": {"ta": "ஜாதகம்", "en": "Horoscope"},
    "birth_chart": {"ta": "ஜன்ம குண்டலி", "en": "Birth Chart"},
    "ascendant": {"ta": "லக்னம்", "en": "Ascendant"},
    "lagna": {"ta": "லக்கினம்", "en": "Lagna"},
    "rasi_chart": {"ta": "ராசி சார்ட்", "en": "Rasi Chart"},
    "navamsa": {"ta": "நவாம்சம்", "en": "Navamsa"},
    "dasa_bhukti": {"ta": "தசா புக்தி", "en": "Dasa Bhukti"},
    "gochara": {"ta": "கோசாரம்", "en": "Gochara"},
    "shanti": {"ta": "சாந்தி", "en": "Shanti"},
    "mangalik": {"ta": "மங்களிகம்", "en": "Mangalik"},
    "panchanga": {"ta": "பஞ்சாங்கம்", "en": "Panchanga"},
    
    # Time Elements (Panchanga)
    "tithi": {"ta": "திதி", "en": "Tithi"},
    "karana": {"ta": "கரணம்", "en": "Karana"},
    "yoga": {"ta": "யோகம்", "en": "Yoga"},
    "vara": {"ta": "வாரம்", "en": "Vara"},
    "nakshatra": {"ta": "நட்சத்திரம்", "en": "Nakshatra"},
    
    # Days of the Week
    "sunday": {"ta": "ஞாயிறு", "en": "Sunday"},
    "monday": {"ta": "திங்கள்", "en": "Monday"},
    "tuesday": {"ta": "செவ்வாய்", "en": "Tuesday"},
    "wednesday": {"ta": "புதன்", "en": "Wednesday"},
    "thursday": {"ta": "வியாழன்", "en": "Thursday"},
    "friday": {"ta": "வெள்ளி", "en": "Friday"},
    "saturday": {"ta": "சனி", "en": "Saturday"},
    
    # Marriage Terms
    "porutham": {"ta": "பொருத்தம்", "en": "Compatibility"},
    "dina_porutham": {"ta": "தின பொருத்தம்", "en": "Day Compatibility"},
    "gana_porutham": {"ta": "கண பொருத்தம்", "en": "Temperament Compatibility"},
    "yoni_porutham": {"ta": "யோனி பொருத்தம்", "en": "Animal Compatibility"},
    "rasi_porutham": {"ta": "ராசி பொருத்தம்", "en": "Zodiac Compatibility"},
    "rasyadhipati_porutham": {"ta": "ராசியதிபதி பொருத்தம்", "en": "Lord of Zodiac Compatibility"},
    "rajju_porutham": {"ta": "ராஜ்ஜு பொருத்தம்", "en": "Longevity Compatibility"},
    "vedha_porutham": {"ta": "வேத பொருத்தம்", "en": "Obstruction Compatibility"},
    "vasya_porutham": {"ta": "வச்சிய பொருத்தம்", "en": "Attraction Compatibility"},
    "mahendra_porutham": {"ta": "மகேந்திர பொருத்தம்", "en": "Progeny Compatibility"},
    "stree_deergha_porutham": {"ta": "ஸ்த்ரீ தீர்க்க பொருத்தம்", "en": "Wife's Longevity Compatibility"},
    
    # Elements 
    "agni": {"ta": "அக்னி", "en": "Fire"},
    "prithvi": {"ta": "பிருத்வி", "en": "Earth"},
    "vayu": {"ta": "வாயு", "en": "Air"},
    "jala": {"ta": "ஜலம்", "en": "Water"},
    "akasha": {"ta": "ஆகாசம்", "en": "Ether"},
        
    # Miscellaneous Terms
    "jataka": {"ta": "ஜாதகம்", "en": "Natal Chart"},
    "graha": {"ta": "கிரகம்", "en": "Planet"},
    "jyotish": {"ta": "ஜோதிடம்", "en": "Astrology"},
    "upagraha": {"ta": "உபகிரகம்", "en": "Sub-planet"},
    "kalapurusha": {"ta": "காலபுருஷ", "en": "Cosmic Man"},
    "ayanamsa": {"ta": "அயனாம்சம்", "en": "Precession"},
    "muhurta": {"ta": "முகூர்த்தம்", "en": "Auspicious Time"},
    "lagna_kundali": {"ta": "லக்ன குண்டலி", "en": "Birth Chart"},
    "bhukti": {"ta": "புக்தி", "en": "Sub-period"},
    "antardasha": {"ta": "அந்தர்தசா", "en": "Sub-sub-period"},
    "sookshma_dasha": {"ta": "சூக்ஷ்ம தசா", "en": "Sub-sub-sub-period"},
    "prana_dasha": {"ta": "பிராண தசா", "en": "Breath Dasha"},
    
    # Extended Marriage Terms
    "ashta_kuta": {"ta": "அஷ்டகூட", "en": "Eight Compatibility Points"},
    "kuja_dosha_shanti": {"ta": "குஜ தோஷ சாந்தி", "en": "Mars Affliction Remedy"},
    "mangal_dosha": {"ta": "மங்கள் தோஷம்", "en": "Mars Affliction"}
}